# Generated by Django 3.1.2 on 2024-11-22 15:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ac_price', models.FloatField()),
                ('non_ac_price', models.FloatField()),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='flight.place')),
            ],
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('room_type', models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], max_length=10)),
                ('price', models.FloatField()),
                ('booking_date', models.DateTimeField(default=datetime.datetime.now)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flight.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CargoService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_type', models.CharField(choices=[('general', 'General Cargo'), ('perishable', 'Perishable Goods'), ('hazardous', 'Dangerous Goods'), ('live_animals', 'Live Animals'), ('valuable', 'Valuable Cargo'), ('oversized', 'Oversized Cargo'), ('fragile', 'Fragile Cargo'), ('documents', 'Documents')], max_length=64)),
                ('max_weight', models.FloatField()),
                ('price_per_kg', models.FloatField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_services', to='flight.flight')),
            ],
        ),
        migrations.CreateModel(
            name='CargoBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('total_price', models.FloatField()),
                ('booking_date', models.DateTimeField(default=datetime.datetime.now)),
                ('cargo_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flight.cargoservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
