# Generated by Django 3.1.2 on 2024-11-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_cargobooking_cargoservice_hotel_hotelbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='num_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
