# Generated by Django 3.1.2 on 2024-11-24 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_hotelreceipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelreceipt',
            name='passengers',
        ),
    ]
