# Generated by Django 3.1.2 on 2024-11-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_hotelreceipt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelreceipt',
            name='checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelreceipt',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
