# Generated by Django 3.1.2 on 2024-11-24 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_auto_20241124_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('icao_code', models.CharField(max_length=4, unique=True)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='cargobooking',
            name='avg_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargoservice',
            name='avg_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargoservice',
            name='cargo_type',
            field=models.CharField(choices=[('general', 'General Cargo'), ('perishable', 'Perishable Goods'), ('hazardous', 'Dangerous Goods'), ('live_animals', 'Live Animals'), ('valuable', 'Valuable Cargo'), ('oversized', 'Oversized Cargo'), ('fragile', 'Fragile Cargo'), ('documents', 'Documents')], default=1, max_length=64),
        ),
        migrations.AlterField(
            model_name='cargoservice',
            name='max_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargoservice',
            name='price_per_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargoservice',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_services', to='flight.airline'),
        ),
    ]
