# Generated by Django 3.1.2 on 2024-11-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0010_auto_20241124_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargobooking',
            name='avg_price',
        ),
        migrations.RemoveField(
            model_name='cargoservice',
            name='avg_price',
        ),
    ]
