# Generated by Django 3.1.2 on 2024-11-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0012_auto_20241124_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargobooking',
            name='email',
            field=models.EmailField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='cargobooking',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cargobooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default=1, max_length=45),
        ),
        migrations.AlterField(
            model_name='hotelreceipt',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default=1, max_length=45),
        ),
    ]
