# Generated by Django 3.1.2 on 2024-11-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0013_auto_20241124_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargobooking',
            name='ref_no',
            field=models.CharField(default=1, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
